### ISSUE TITLE
Getting CORS issue

### ISSUE THREAD

**Issue by webacers** [knoxpo/razorpay-typescript#1]
Hi, 
I am getting CORS issue when trying to create Order. 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.razorpay.com/v1/orders?amount=5000&receipt=123&payment_capture=1&currency=INR. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Is there any solution?

**Comment by nhathiwala** [comment]
You may try adding CORS headers while initializing.

````ts
const razorConfig = {
    authKey: {
        key_id: process.env.KEY_ID, // your `KEY_ID`
        key_secret: process.env.KEY_SECRET // your `KEY_SECRET`
    },
    headers: {}  // <---- Here
};
const rzp = new Razorpay(razorConfig);
````

I think this will work, so closing this issue.

**Comment by webacers** [comment]
Thank you for the reply. 
However, I tried using following headers but still getting CORS issue. 

` 'content-type:': 'application/json',        
 `
Is there any other header which need to be set?

**Comment by nhathiwala** [comment]
Refer to [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)
